name: Build

on:
  workflow_call:
    secrets:
      SECRET:
        required: true

jobs:
  build-linux:
    name: "Build for linux"
    runs-on: ubuntu-latest

    container:
      image: golang:alpine

    steps:
    - name: "Install packages"
      run: apk update && apk add --no-cache libpcap-dev musl-dev gcc

    - uses: actions/checkout@v3

    - name: "Create output path"
      run: mkdir ./output

    - name: "Restore cache"
      uses: actions/cache/restore@v3
      id: restore-cache
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

    - name: "Build for amd46 (64 bit)"
      working-directory: ./src
      env:
        CGO_ENABLED: 1
        GOARCH: amd64
        GOOS: linux
      run: |
        go build -ldflags '-linkmode external -extldflags "-static"' -o ../output/backend-linux-64

    - name: "Uplaod artifacts"
      uses: actions/upload-artifact@v2
      with:
        name: backend-linux
        path: ./output/backend-linux-64

  build-windows:
    name: "Build for windows"
    runs-on: windows-latest


    steps:
    - uses: actions/checkout@v3

    - name: "Load secret"
      env:
        SECRET: ${{ secrets.SECRET }}
      run: |
        echo "$env:SECRET" > .\src\excel_adapter\internals\secret.json

    - name: "Create output path"
      run: mkdir .\output

    - name: "Restore cache"
      uses: actions/cache/restore@v3
      id: restore-cache
      with:
        path: |
          ~\AppData\Local\go-build
          ~\go\pkg\mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

    - name: "Build for amd46 (64 bit)"
      working-directory: .\src
      env:
        CGO_ENABLED: 1
        GOARCH: amd64
        GOOS: windows
      run: |
        go build -ldflags '-linkmode external -extldflags "-static"' -o ..\output\backend-windows-64.exe

    - name: "Save cache"
      uses: actions/cache/save@v3
      with:
        path: |
          ~\AppData\Local\go-build
          ~\go\pkg\mod
        key: ${{ steps.restore-cache.outputs.cache-primary-key }}

    - name: "Uplaod artifacts"
      uses: actions/upload-artifact@v2
      with:
        name: backend-windows
        path: ./output/backend-windows-64.exe
